### ISSUE TITLE
Symfony container collection type count bug 

### ISSUE THREAD

**Issue by zacharylund** [phpstan/phpstan-symfony#158]
Version 0.12.29 and 0.12.30 may have introduced some bugs regarding container parameter checking.

I created a brand new Symfony 5.2 project, installed PHPStan and the Symfony extension, and created a basic config file to specify the container_xml_path.

Then I added this to config/services.yaml:

```yaml
parameters:
   test_bool: true
   test_collection: {}
```
And this to a controller:

```php
$testBool = $this->getParameter('test_bool');
$testCollection = $this->getParameter('test_collection');

// PHPStan Symfony 0.12.29: If condition is always true.
// PHPSTan Symfony 0.12.30: No error.
if ($testBool) {
    echo 'test bool is true';
}

// PHPStan Symfony 0.12.29 and 0.12.30 show no errors.
if (0 === count($testCollection)) {
    echo 'test collection is empty.';
}

// PHPStan Symfony 0.12.29 and 0.12.30 say: Strict comparison using !== between 0 and 0 will always evaluate to false.
if (0 !== count($testCollection)) {
    echo 'test collection is not empty';
}

// PHPStan Symfony 0.12.29 and 0.12.30 say: Comparison operation ">" between 0 and 0 is always false.
if (count($testCollection) > 0) {
    echo 'test collection is not empty';
}
```

The output doesn't make sense.

PHPStan should either throw errors for all four of these if statements or none of them.

Given that parameters are configurable, I think checking to make sure a collection has at least one element should be valid.

At a minimum, checking the count of a collection should behave the same regardless of the operation.

Edit: phpstan-symfony 0.12.28 outputs no errors. I used level 4 for all checks.

**Comment by ondrejmirtes** [comment]
Please show how the dumped test_collection looks like in the provided XML container, thanks.

**Comment by zacharylund** [comment]
```
<?xml version="1.0" encoding="utf-8"?>
<container xmlns="http://symfony.com/schema/dic/services" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://symfony.com/schema/dic/services https://symfony.com/schema/dic/services/services-1.0.xsd">
  <parameters>
    ...
    <parameter key="test_collection" type="collection"/>
    <parameter key="test_bool">true</parameter>
    ...
  </parameters>
</container>
```

**Comment by ondrejmirtes** [comment]
Fixed: https://github.com/phpstan/phpstan-symfony/commit/ebf89e81c60e3c7a0417fa5166fd6da50139dde5

Released in 0.12.31.

**Comment by zacharylund** [comment]
@ondrejmirtes Thanks for taking a look at this so quickly. That fixed the empty checks against an empty collection. However, here's a more thorough example run against 0.12.31. A collection with values still fails empty checks.

config/services.yaml:
```yaml
parameters:
    empty_collection: {}
    non_empty_collection:
        - value
```

var/cache/dev/App_KernelDevDebugContainer.xml:
```xml
<?xml version="1.0" encoding="utf-8"?>
<container xmlns="http://symfony.com/schema/dic/services" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://symfony.com/schema/dic/services https://symfony.com/schema/dic/services/services-1.0.xsd">
  <parameters>
    <parameter key="empty_collection" type="collection"/>
    <parameter key="non_empty_collection" type="collection">
      <parameter>value</parameter>
    </parameter>
  </parameters>
</container>
```

```php
        $emptyCollection = $this->getParameter('empty_collection');

        if (0 === count($emptyCollection)) {
            echo 'empty collection is empty.';
        }

        if (0 !== count($emptyCollection)) {
            echo 'empty collection is not empty';
        }

        if (count($emptyCollection) > 0) {
            echo 'empty collection is not empty';
        }

        $nonEmptyCollection = $this->getParameter('non_empty_collection');

        // Strict comparison using === between 0 and int<1, max> will always evaluate to false.
        if (0 === count($nonEmptyCollection)) {
            echo 'non-empty collection is empty.';
        }

        if (0 !== count($nonEmptyCollection)) {
            echo 'non-empty collection is not empty';
        }

        // Comparison operation ">" between int<1, max> and 0 is always true.
        if (count($nonEmptyCollection) > 0) {
            echo 'non-empty collection is not empty';
        }
```

**Comment by ondrejmirtes** [comment]
Alright: https://github.com/phpstan/phpstan-symfony/commit/bb80b1be3debd0ea1bd1486676cfc568155dc0b1 released in 0.12.32.

**Comment by zacharylund** [comment]
Perfect! Thank you very much!
